def line():
  A = float (input ("ingrese el coeficiente A: "))
  B = float (input ("ingrese el coeficiente B: "))
  X1 = float (input ("ingrese el coeficiente X1: "))
  X2 = float (input ("ingrese el coeficiente X2: "))
  Print (f" El coeficinete A de su ecuacion de la recta es: {A}")
  Print (f" El coeficinete A de su ecuacion de la recta es: {B}")
  Print (f" El coeficinete A de su ecuacion de la recta es: {X1}")
  Print (f" El coeficinete A de su ecuacion de la recta es: {X2}")
  Print("\n")
  Print ("Para la siguinete ecuación:")
  Print(f"\t y= {A}X + {B}")
  Print("\n")
  Print (f"Dados los siguientes puntos:")
  Y1= A*X1+B
  Y2= A*X2+B
  Print (f"\tP1({X1}, {Y1}))
  Print (f"\tP2({X2}, {Y2}))
  Print ("\n")
  distancia = ((X1-X2)**2+(Y1-Y2)**2)**(1/2)
  print(f"La distancia entre ellos es:{distancia}")
